#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"

readonly DOTBOT_DIR='dotbot'
readonly DOTBOT_BIN='bin/dotbot'
readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly ARGS="$@"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

run_dotbot () {
  local config
  config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    --plugin-dir dotbot-brewfile \
    -c "$config" $ARGS
}

run_dotbot 'steps/macos.yml' || true
run_dotbot 'steps/homebrew.yml' || true
run_dotbot 'steps/iterm.yml' || true
run_dotbot 'steps/vscode.yml' || true
run_dotbot 'steps/javascript.yml' || true
run_dotbot 'steps/complete.yml' || true
