#
# Homebrew
#


#
# Development
#

brew 'git'
#brew 'git-extras'
#brew 'gh'
brew 'volta'


#
# Utilities
#

#brew 'imagemagick'
#brew 'jpeg'

#
# Homebrew Cask
#


tap 'homebrew/cask'
cask_args appdir: '/Applications'


#
# Essentials
#

#http://www.alfredapp.com/
#cask 'alfred'

#https://www.dropbox.com/
#cask 'dropbox'

#http://www.shirt-pocket.com/SuperDuper/SuperDuperDescription.html
cask 'superduper'

#https://www.expressvpn.com
cask 'expressvpn'


#
# Development
#

#http://imageoptim.com/
#cask 'imageoptim'

#https://iterm2.com
cask 'iterm2'

#https://code.visualstudio.com
cask 'visual-studio-code' 

#http://www.sublimetext.com/3
#cask 'sublime-text'


#
# Browsers
#

#https://www.google.com/chrome/downloads/
cask 'google-chrome'

#https://www.google.com/chrome/canary/
#cask 'google-chrome-canary'

#http://www.chromium.org/
#cask 'chromium'

#http://www.mozilla.org/en-US/firefox/new/
cask 'firefox'

#https://www.microsoft.com/en-us/edge
#cask 'microsoft-edge'


#
# Others
#

#http://www.figma.com
cask 'figma'

#https://rectangleapp.com/pro
cask 'rectangle-pro'

#http://www.bohemiancoding.com/sketch/
#cask 'sketch'

#https://playbeta.pocketcasts.com/
#cask 'pocket-casts'

#http://stellarium.org/
#cask 'stellarium'

#http://dropdox.com
#cask 'dropbox'

#https://www.coconut-flavour.com/coconutbattery/
#cask 'coconutbattery'

#https://justgetflux.com
#cask 'flux'


#
# Mac App Store
#

mas '1Password7', id: 1333542190
mas 'Bear', id: 1091189122
mas 'DaisyDisk', id: 411643860
mas 'Darkroom', id: 953286746
mas 'Fantastical', id: 975937182
mas 'iA Writer', id: 775737590
mas 'Meeter', id: 1510445899
mas 'Patterns', id: 429449079
mas 'Pixelmator', id: 407963104
mas 'Poolsuite FM', id: 1514817810
mas 'Shush', id: 496437906
mas 'Slack', id: 803453959 
mas 'Spark', id: 1176895641
