# Oh-My-Zsh configuration
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

# Treat hyphens and underscores as interchangeable in completion
HYPHEN_INSENSITIVE="true"

# Show dots while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Don't mark untracked files as dirty (speeds up prompt in large repos)
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git node zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Environment
export EDITOR='vim'
export VISUAL='code --wait'

# Aliases
alias gdstat="git diff --stat"

# Load mise (before setup scripts) in case it's the first time installing them
eval "$(mise activate zsh)"
